[phases.build]
aptPkgs = ["wget"]
cmds = ['pnpm run build', 'pnpx @posthog/cli --dotenv-file .env.dynamic sourcemap inject --directory ./build', 'pnpx @posthog/cli --dotenv-file .env.dynamic sourcemap upload --directory ./build --delete-after']