#!/usr/bin/env node

import fs from 'node:fs/promises';
import path from 'node:path';

const port = process.env.CAP_STANDALONE_PORT ?? '3001';
const apiKey = process.env.CAP_API_KEY;
const base = `http://localhost:${port}`;
const envFile = path.join(process.cwd(), '.env.e2e');

async function main() {
  console.log('[captcha-setup] waiting for Cap at', base);

  const isUp = await waitForCap(base, 20000);
  if (!isUp) {
    console.error('[captcha-setup] Cap not reachable at', base);
    process.exit(2);
  }

  const keyName = `e2e-captcha-${Date.now()}`;

  try {
    // Create a new key
    console.log('[captcha-setup] creating captcha key via API');
    const createResponse = await fetch(`${base}/server/keys`, {
      body: JSON.stringify({ name: keyName }),
      headers: {
        Authorization: `Bot ${apiKey}`,
        'Content-Type': 'application/json'
      },
      method: 'POST'
    });

    if (!createResponse.ok) {
      const text = await createResponse.text();
      console.error('[captcha-setup] failed to create key:', createResponse.status, text);
      process.exit(3);
    }

    // List keys to find the one we just created
    const listResponse = await fetch(`${base}/server/keys`, {
      headers: { Authorization: `Bot ${apiKey}` }
    });

    if (!listResponse.ok) {
      const text = await listResponse.text();
      console.error('[captcha-setup] failed to list keys:', listResponse.status, text);
      process.exit(4);
    }

    const keys = await listResponse.json();
    console.log('[captcha-setup] keys response:', JSON.stringify(keys, null, 2));

    // Find our key
    let siteKey = null;
    if (Array.isArray(keys)) {
      const ourKey = keys.find((k) => k.name === keyName);
      if (ourKey) {
        siteKey = ourKey.siteKey;
      }
    }

    if (!siteKey) {
      console.error('[captcha-setup] could not find siteKey in response');
      process.exit(5);
    }

    // Rotate the secret to generate a proper secret key
    console.log('[captcha-setup] rotating secret for siteKey:', siteKey);
    const rotateResponse = await fetch(`${base}/server/keys/${siteKey}/rotate-secret`, {
      headers: { Authorization: `Bot ${apiKey}` },
      method: 'POST'
    });

    console.log('[captcha-setup] rotate response status:', rotateResponse.status);

    let secret = null;
    if (rotateResponse.ok) {
      // Try to get the secret from the rotate response
      const rotateText = await rotateResponse.text();
      console.log('[captcha-setup] rotate response body:', rotateText);

      // Try to parse as JSON if there's content
      if (rotateText.trim()) {
        try {
          const rotateData = JSON.parse(rotateText);
          console.log('[captcha-setup] rotate response JSON:', JSON.stringify(rotateData, null, 2));
          secret = rotateData.secretKey || rotateData.secret || rotateData.siteSecret || rotateData.key?.secret;
        } catch {
          console.log('[captcha-setup] rotate response is not JSON, treating as plain text');
          // Maybe the secret is returned as plain text
          secret = rotateText.trim();
        }
      }
    } else {
      const errorText = await rotateResponse.text();
      console.error('[captcha-setup] failed to rotate secret:', rotateResponse.status, errorText);
    }

    // If we didn't get the secret from rotate response, fetch key details
    if (!secret) {
      console.log('[captcha-setup] fetching key details for secret after rotation:', siteKey);
      const detailResponse = await fetch(`${base}/server/keys/${siteKey}`, {
        headers: { Authorization: `Bot ${apiKey}` }
      });

      if (detailResponse.ok) {
        const detail = await detailResponse.json();
        console.log('[captcha-setup] key details after rotation:', JSON.stringify(detail, null, 2));
        secret = detail.secret || detail.siteSecret || detail.key?.secret;
      }
    }

    if (!secret) {
      console.error('[captcha-setup] failed to get secret after rotation');
      process.exit(7);
    }

    // Write environment file
    const envContent = `# Generated by setup-captcha.mjs for e2e tests
PUBLIC_CAPTCHA_SITE_KEY="${siteKey}"
CAPTCHA_SITE_SECRET="${secret}"
PUBLIC_CAPTCHA_ENDPOINT="http://localhost:3001"
`;

    await fs.writeFile(envFile, envContent, 'utf8');

    console.log('[captcha-setup] captcha configured successfully');
    console.log(`[captcha-setup] site key: ${siteKey}`);
    console.log(`[captcha-setup] secret: ${secret}`);
    console.log(`[captcha-setup] environment file: ${envFile}`);
  } catch (error) {
    console.error('[captcha-setup] error:', error);
    process.exit(10);
  }
}

async function waitForCap(url, timeout = 15000) {
  const start = Date.now();
  while (Date.now() - start < timeout) {
    try {
      const res = await fetch(url);
      if (res.ok) return true;
    } catch {
      // ignore
    }
    await new Promise((r) => setTimeout(r, 500));
  }
  return false;
}

main();
