services:
  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
      args:
        PB_VERSION: '0.29.2'
        PB_ARCH: 'amd64'
    image: opencommunities-pocketbase:local
    network_mode: 'host'
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pb_migrations:/pb/pb_migrations
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '8025:8025'
      - '1025:1025'

  cap:
    image: tiago2/cap:latest
    environment:
      - ADMIN_KEY=${CAP_ADMIN_KEY:-b622695b-1e2c-42f7-87b2-b442049c679a}
    ports:
      - '3001:3000'
    volumes:
      - ./cap/data:/usr/src/app/.data
