name: Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  PROSOPO_SECRET: ${{ secrets.PROSOPO_SECRET }}
  PUBLIC_API_ENDPOINT: ${{ vars.PUBLIC_API_ENDPOINT }}
  PUBLIC_HOSTNAME: ${{ vars.PUBLIC_HOSTNAME }}
  PUBLIC_PROSOPO_SITEKEY: ${{ vars.PUBLIC_PROSOPO_SITEKEY }}
  PUBLIC_SENTRY_DSN: ${{ vars.PUBLIC_SENTRY_DSN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_ORG: ${{ vars.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_TOKEN }}

      - name: Build and push Docker images
        uses: iloveitaly/github-action-nixpacks@main
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Deploy to Coolify
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
