name: Deploy

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_TOKEN }}

      - name: Deploy PB hooks to PocketHost
        env:
          PHIO_USERNAME: ${{ secrets.POCKETHOST_EMAIL }}
          PHIO_PASSWORD: ${{ secrets.POCKETHOST_PASSWORD }}
        run: |
          npm install -g phio
          phio deploy -v

      - name: Deploy to Coolify
        env:
          COOLIFY_WEBHOOK: ${{ secrets.COOLIFY_WEBHOOK }}
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
        run: |
          curl --request GET "$COOLIFY_WEBHOOK" \
            --header "Authorization: Bearer $COOLIFY_TOKEN"

      - name: Promote commit image to latest
        run: |
          COMMIT_SHA="${{ github.event.workflow_run.head_sha }}"
          docker pull ghcr.io/${{ github.repository }}:$COMMIT_SHA
          docker tag ghcr.io/${{ github.repository }}:$COMMIT_SHA ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
